---
title: "Merge 10x Genomics scRNA-seq .h5 files generated by split_h5_by_hash.Rmd"
author: 
 - Lucas Graybuck
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document:
    df_print: paged
    self_contained: true
params:
  in_dir: NULL
  out_dir: NULL
---

```{r Load Libraries}
start_time <- Sys.time()

quiet_library <- function(...) {
  suppressPackageStartupMessages(library(...))
}
quiet_library(rhdf5)
quiet_library(H5weaver)
quiet_library(Matrix)
```

Declaring start
```{r Declare start}
stm("Merging .h5 files")
```

Argument parsing
```{r Parse arguments}
if(is.null(params$in_dir)) {
  in_dir <- system.file("testdata/splitdata", package = "H5weaver")
  out_dir <- tempdir()
} else {
  in_dir <- params$in_dir
  out_dir <- params$out_dir
}

stm(paste0("IN  H5 directory    : ", in_dir))
stm(paste0("OUT Directory       : ", out_dir))
```

```{r Print Arguments}
print(c(
  paste0("IN  H5 directory    : ", in_dir),
  paste0("OUT Directory       : ", out_dir)
))
```

Locate input files
```{r Locate inputs}
in_file_names <- list.files(in_dir, 
                            pattern = "_.+h5$")
# Check for per-well directories
if(length(in_file_names) == 0) {
  in_file_dirs <- list.dirs(in_dir, 
                            recursive = FALSE)
  in_file_names <- unlist(lapply(in_file_dirs,
                                 list.files, 
                                 pattern = "_.+h5$"))
  in_file_paths <- unlist(lapply(in_file_dirs,
                                 list.files,
                                 pattern = "_.+h5$", 
                                 full.names = TRUE))
} else {
  in_file_paths <- list.files(in_dir, 
                              pattern = "_.+h5$", 
                              full.names = TRUE)
}

stm(paste0("Found ", length(in_file_paths), " .h5 files for processing"))
print(paste0("Found ", length(in_file_paths), " .h5 files for processing"))
```

Identify hashes in in_dir
```{r Identify hashes}
in_file_hashes <- sub(".h5$","",sub(".+_","",in_file_names))
unique_hashes <- unique(in_file_hashes)

stm(paste0("Identified ", length(unique_hashes), " hash patterns: ", paste(unique_hashes, collapse = ", ")))
```

Merge files based on hashes
```{r Load Count Matrix}
meta_list <- list()
for(i in seq_along(unique_hashes)) {
  current_hash <- unique_hashes[i]
  stm(paste0("Merging for hash ", current_hash))
  current_files <- in_file_paths[in_file_hashes == current_hash]
  for(f in current_files) {
    stm(paste0("IN  H5 file         : ", f))
  }
  
  h5_ll <- lapply(current_files,
                  h5dump)
  
  h5_list <- reduce_h5_list(h5_ll,
                            sparse_matrices = c("matrix","hash"))
  
  meta_list[[current_hash]] <- h5_list_cell_metadata(h5_list)
  
  out_file <- file.path(out_dir, paste0(current_hash, ".h5"))
  stm(paste0("Writing HDF5 to     : ", out_file))

  write_h5_list(h5_list,
                out_file,
                overwrite = TRUE)
  
  # transposed version for visualization
  h5_list <- h5_list_transpose(h5_list,
                               sparse_matrices = c("matrix","hash"))
  t_out_file <- file.path(out_dir, paste0("transposed_",current_hash, ".h5"))
  stm(paste0("Writing HDF5 to     : ", t_out_file))

  write_h5_list(h5_list,
                t_out_file,
                overwrite = TRUE)
} 

all_meta <- do.call("rbind", meta_list)
```

Plot distribution of samples per well and wells per sample:
```{r}
all_meta <- as.data.table(all_meta)
singlet_meta <- all_meta[hto_category == "singlet"]
```


```{r Session Info}
sessionInfo()
```

Total time elapsed
```{r Show Time}
end_time <- Sys.time()
diff_time <- end_time - start_time
time_message <- paste0("Elapsed Time: ", 
                       round(diff_time, 3),
                       " ", units(diff_time))
print(time_message)
stm(time_message)
stm("H5 merge process complete.")
```
