#' Add cell IDs to a h5_list object
#'
#' @param h5_list a list object generated by running rhdf5::h5dump() on a 10x HDF5 file.
#' @param add_uuid a logical indicating whether or not to add a uuid generated by ids::uuid(). Default is TRUE.
#' @param replace_barcode a logical indicating whether or not the new uuid should replace the barcodes slot. Default is TRUE.
#' @param retain_original_barcode a logical indicating whether to retain the original barcodes if replace_barcode is TRUE. These will be moved to /matrix/original_barcode if TRUE. Default is TRUE.
#' @param add_name a logical indicating whether to add a new cell name. These are adjective_adjective_animal names generated by ids::adjective_animal(). Default is TRUE.
#'
#' @return a modified h5_list object
#' @export
#'
add_cell_ids <- function(h5_list,
                         add_uuid = TRUE,
                         replace_barcode = TRUE,
                         retain_original_barcode = TRUE,
                         add_name = TRUE) {
  assertthat::assert_that(class(h5_list) == "list")
  assertthat::assert_that("matrix" %in% names(h5_list))

  assertthat::assert_that(is.logical(add_uuid))
  assertthat::assert_that(is.logical(add_name))

  if(add_uuid) {

    if(replace_barcode) {
      if(retain_original_barcode) {
        h5_list$matrix$original_barcodes <- h5_list$matrix$barcode
      }
      h5_list$matrix$barcodes <- ids::uuid(n = length(h5_list$matrix$barcodes),
                                           drop_hyphens = TRUE,
                                           use_time = TRUE)
    } else {
      h5_list$matrix$cell_uuid <- ids::uuid(n = length(h5_list$matrix$barcodes),
                                            drop_hyphens = TRUE,
                                            use_time = TRUE)
    }

  }

  if(add_name) {
    h5_list$matrix$cell_name <- ids::adjective_animal(n = length(h5_list$matrix$barcodes),
                                                      n_adjectives = 2,
                                                      max_len = 10)
  }

  h5_list

}

#' Split a 10x HDF5 file based on HTOparser results
#'
#' @param h5_file a character object specifying the location of a 10x Genomics .h5 file.
#' @param hash_category_table a data.frame or data.table with results from HTOparser::categorize_binary_hash_matrix() consisting of 3 columns: cell_barcode, hto_category, and hto_barcode.
#' @param hash_count_matrix (optional) a matrix or dgCMatrix with results from CITE-seq-Count, HTOparser::add_missing_hto_rows(), or HTOparser::barcode_table_to_matrix().
#'
#' @return A list object with contents of the input h5_file separated by each hto_barcode. Also includes multiplets.
#' @export
#'
split_h5_list_by_hash <- function(h5_list,
                             hash_category_table,
                             hash_count_matrix = NULL,
                             add_uuid = TRUE,
                             add_name = TRUE,
                             well_id = NULL) {

  assertthat::assert_that(class(h5_list) == "list")

  assertthat::assert_that(sum(class(hash_category_table) %in% c("data.frame","data.table")) > 0)

  if(!is.null(hash_count_matrix)) {
    assertthat::assert_that(class(hash_count_matrix) %in% c("dgCMatrix","matrix"))
  }

  assertthat::assert_that(is.logical(add_uuid))
  assertthat::assert_that(is.logical(add_name))

  if(add_uuid) {
    h5_list <- add_cell_ids(h5_list,
                            add_uuid = TRUE,
                            replace_barcode = TRUE,
                            retain_original_barcode = TRUE,
                            add_name = FALSE)
  }

  if(add_name) {
    h5_list <- add_cell_ids(h5_list,
                            add_uuid = FALSE,
                            add_name = TRUE)
  }

  if(!is.null(well_id)) {
    assertthat::assert_that(is.character(well_id))
    assertthat::assert_that(length(well_id) == 1)

    h5_list$matrix$well_id <- rep(well_id, length(h5_list$matrix$barcodes))
  }

  h5_list$matrix$original_barcodes <- sub("-.+","",h5_list$matrix$original_barcodes)
  common_barcodes <- intersect(h5_list$matrix$original_barcodes, hash_category_table$cell_barcode)

  common_hash_table <- hash_category_table[hash_category_table$cell_barcode %in% common_barcodes,]

  singlet_hash_table <- common_hash_table[common_hash_table$hto_category == "singlet",]
  multiplet_hash_table <- common_hash_table[common_hash_table$hto_category != "singlet",]

  hto_barcodes <- unique(as.character(singlet_hash_table$hto_barcode))

  h5_list <- h5_list_convert_to_dgCMatrix(h5_list)

  split_h5_list <- list()
  for(barcode in hto_barcodes) {
    hto_hash_table <- singlet_hash_table[singlet_hash_table$hto_barcode == barcode,]

    split_h5_list[[barcode]] <- subset_h5_list_by_barcodes(h5_list,
                                                               hto_hash_table$cell_barcode,
                                                               original_barcodes = TRUE)

    split_h5_list[[barcode]] <- h5_list_convert_from_dgCMatrix(split_h5_list[[barcode]])

    if(!is.null(hash_count_matrix)) {
      hto_hash_matrix <- hash_count_matrix[, hto_hash_table$cell_barcode]
      hto_hash_matrix <- as(hto_hash_matrix, "dgCMatrix")
      colnames(hto_hash_matrix) <- split_h5_list[[barcode]]$matrix$barcode[match(colnames(hto_hash_matrix),
                                                                                 split_h5_list[[barcode]]$matrix$original_barcode)]

      split_h5_list[[barcode]] <- h5_list_add_dgCMatrix(split_h5_list[[barcode]],
                                                        mat = hto_hash_matrix,
                                                        target = "hash_count_matrix")
    }

  }

  split_h5_list$multiplet <- subset_h5_list_by_barcodes(h5_list,
                                                        multiplet_hash_table$cell_barcode,
                                                        original_barcodes = TRUE)
  split_h5_list$multiplet <- h5_list_convert_from_dgCMatrix(split_h5_list$multiplet)
  if(!is.null(hash_count_matrix)) {
    multiplet_hash_matrix <- hash_count_matrix[, multiplet_hash_table$cell_barcode]
    multiplet_hash_matrix <- as(multiplet_hash_matrix, "dgCMatrix")
    colnames(multiplet_hash_matrix) <- split_h5_list$multiplet$matrix$barcode[match(colnames(multiplet_hash_matrix),
                                                                                    split_h5_list$multiplet$matrix$original_barcode)]

    split_h5_list$multiplet <- h5_list_add_dgCMatrix(split_h5_list$multiplet,
                                                     mat = multiplet_hash_matrix,
                                                     target = "hash_count_matrix")
  }

  split_h5_list
}

#' Subset a h5_list object based on a set of barcodes.
#'
#' @param h5_list a list object generated by running rhdf5::h5dump() on a 10x HDF5 file, with a matrix converted by h5_list_convert_to_dgCMatrix().
#' @param barcodes a set of barcodes to select for filtering
#' @param original_barcodes a logical indicating if the original_barcodes object should be used instead of barcodes (in case uuids have replaced original barcodes)
#'
#' @return a list object
#' @export
#'
subset_h5_list_by_barcodes <- function(h5_list,
                                       barcodes,
                                       original_barcodes = FALSE) {
  assertthat::assert_that(class(h5_list) == "list")
  assertthat::assert_that("matrix" %in% names(h5_list))
  assertthat::assert_that("h5_dgCMatrix" %in% names(h5_list))

  if(original_barcodes) {
    keep <- match(barcodes, h5_list$matrix$original_barcodes)
  } else {
    keep <- match(barcodes, colnames(h5_list$h5_dgCMatrix))
  }

  h5_list$h5_dgCMatrix <- h5_list$h5_dgCMatrix[, keep]

  additional_cell_values <- names(h5_list$matrix)[names(h5_list$matrix) != "features"]

  for(additional_value in additional_cell_values) {
    h5_list$matrix[[additional_value]] <- h5_list$matrix[[additional_value]][keep]
  }

  h5_list
}

#' Convert the matrix in an h5_list from 10x Genomics data to a sparse matrix
#'
#' This is very useful for subsetting the matrix based on column names.
#'
#' @param h5_list a list object generated by running rhdf5::h5dump() on a 10x HDF5 file.
#'
#' @return a list object
#' @export
#'
h5_list_convert_to_dgCMatrix <- function(h5_list) {
  assertthat::assert_that(class(h5_list) == "list")
  assertthat::assert_that("matrix" %in% names(h5_list))

  h5_list[["h5_dgCMatrix"]] <- Matrix::sparseMatrix(x = h5_list$matrix$data,
                                                  i = h5_list$matrix$indices,
                                                  index1 = FALSE,
                                                  p = h5_list$matrix$indptr,
                                                  dims = h5_list$matrix$shape,
                                                  dimnames = list(h5_list$matrix$features$id,
                                                                  h5_list$matrix$barcodes))
  h5_list$matrix$data <- NULL
  h5_list$matrix$indices <- NULL
  h5_list$matrix$indptr <- NULL
  h5_list$matrix$shape <- NULL
  h5_list$matrix$features$id <- NULL
  h5_list$matrix$barcodes <- NULL

  h5_list
}

#' Convert the matrix in an h5_list from a sparse matrix back to its original structure
#'
#' This is very useful for preparing to write back out to an .h5 file.
#'
#' @param h5_list a list object generated by running rhdf5::h5dump() on a 10x HDF5 file, with a matrix converted by h5_list_convert_to_dgCMatrix().
#'
#' @return a list object
#' @export
#'
h5_list_convert_from_dgCMatrix <- function(h5_list) {

  assertthat::assert_that(class(h5_list) == "list")
  assertthat::assert_that("matrix" %in% names(h5_list))
  assertthat::assert_that("h5_dgCMatrix" %in% names(h5_list))

  h5_list$matrix$data <- h5_list$h5_dgCMatrix@x
  h5_list$matrix$indices <- h5_list$h5_dgCMatrix@i
  h5_list$matrix$indptr <- h5_list$h5_dgCMatrix@p
  h5_list$matrix$shape <- dim(h5_list$h5_dgCMatrix)
  h5_list$matrix$barcodes <- colnames(h5_list$h5_dgCMatrix)
  h5_list$matrix$features$id <- rownames(h5_list$h5_dgCMatrix)

  h5_list$h5_dgCMatrix <- NULL

  h5_list
}

#' Add a sparse matrix to an h5_list containing 10x genomics data
#'
#' @param h5_list a list object, usually generated by running rhdf5::h5dump() on a 10x HDF5 file.
#' @param mat a dgCMatrix to add to the h5_list
#' @param target a character object specifying the location within the list to write to.
#'
#' @return a list object with the additional matrix added similar to 10x HDF5 matrix format.
#' @export
#'
h5_list_add_dgCMatrix <- function(h5_list,
                                  mat,
                                  target) {

  assertthat::assert_that(class(h5_list) == "list")
  assertthat::assert_that(class(mat) == "dgCMatrix")

  h5_list[[target]]$data <- mat@x
  h5_list[[target]]$indices <- mat@i
  h5_list[[target]]$indptr <- mat@p
  h5_list[[target]]$shape <- dim(mat)
  h5_list[[target]]$barcodes <- colnames(mat)
  h5_list[[target]]$features <- list(id = rownames(mat))

  h5_list
}

